### ISSUE TITLE
FEAT: Create switch slide button

### ISSUE THREAD

**Issue by Gabz047** [fabricadesoftware-ifc/fabricaHistologia_frontend#30]
Switch off

![Image](https://github.com/user-attachments/assets/edca0a25-f01e-46b6-be68-52b0a62e17d4)

Switch on

![Image](https://github.com/user-attachments/assets/5a8450b7-6477-4159-9503-0b4e97de4da8)

Entire component

![Image](https://github.com/user-attachments/assets/3da137e5-e279-40e9-8f18-1def367aa8f9)

**Comment by mateus-lopes** [comment]
complete
